#include "picto_internal.h"

/* The pictograms a top bar shows, drawn again on a 24x24 grid: where 2
 * cells are too small for the 16 px art twice (28x30 px on a screen scaled
 * 1.5) the small one sat lost in its box. The rest (the widget column's:
 * sun, lamp, disks, lock, note, drop, the sky) have only the 16 px art. */

#define N CTUI_LOOK_PICTO_GRID_BIG
#define ART24(name, ...)                                                       \
  static const char name[] = __VA_ARGS__;                                      \
  _Static_assert(sizeof name == N * N + 1, #name " is 24x24")
/* one picto.c reads by name */
#define ART24X(name, ...)                                                      \
  const char name[] = __VA_ARGS__;                                             \
  _Static_assert(sizeof name == N * N + 1, #name " is 24x24")

ART24(SPEAKER, "........................"
               "........................"
               "..........tt............"
               ".........tht.......3...."
               "........thht........3..."
               ".......thhht....2....3.."
               "......thhhht.....2...3.."
               "tttttthhhhht..1...2...3."
               "thhhhhhhhhht...1..2...3."
               "thhhhhhhhhht...1...2..3."
               "thhhhhhhhhht....1..2..3."
               "thhhhhhhhhht....1..2..3."
               "thhhhhhhhhst....1..2..3."
               "thhhhhhhhhst....1..2..3."
               "thhhhhhhhsst...1...2..3."
               "thhhhhhhssst...1..2...3."
               "ttttttssssst..1...2...3."
               "......tsssst.....2...3.."
               ".......tssst....2....3.."
               "........tsst........3..."
               ".........tst.......3...."
               "..........tt............"
               "........................"
               "........................");

/* over a muted speaker's waves */
ART24X(ctui_look_picto_big_cross, "........................"
                                  "........................"
                                  "........................"
                                  "........................"
                                  "........................"
                                  "........................"
                                  "........................"
                                  ".............tt......tt."
                                  "..............tt....tt.."
                                  "...............tt..tt..."
                                  "................tttt...."
                                  ".................tt....."
                                  ".................tt....."
                                  "................tttt...."
                                  "...............tt..tt..."
                                  "..............tt....tt.."
                                  ".............tt......tt."
                                  "........................"
                                  "........................"
                                  "........................"
                                  "........................"
                                  "........................"
                                  "........................"
                                  "........................");

ART24(MIC, "........................"
           ".........tttttt........."
           "........thhhhhst........"
           "........thhhhhst........"
           "........thhhhhst........"
           "........thhhhhst........"
           "........thhhhhst........"
           "........thhhhhst........"
           "........thhhhhst........"
           ".....t..thhhhhst..t....."
           ".....t..thhhhhst..t....."
           ".....t..thhhhsst..t....."
           ".....t..thssssst..t....."
           ".....tt..tttttt..tt....."
           "......tt........tt......"
           ".......ttt....ttt......."
           ".........tttttt........."
           "...........tt..........."
           "...........tt..........."
           "...........tt..........."
           "...........tt..........."
           ".......tttttttttt......."
           ".......tttttttttt......."
           "........................");

/* through a muted mic */
ART24X(ctui_look_picto_big_slash, "........................"
                                  ".tt....................."
                                  "..tt...................."
                                  "...tt..................."
                                  "....tt.................."
                                  ".....tt................."
                                  "......tt................"
                                  ".......tt..............."
                                  "........tt.............."
                                  ".........tt............."
                                  "..........tt............"
                                  "...........tt..........."
                                  "............tt.........."
                                  ".............tt........."
                                  "..............tt........"
                                  "...............tt......."
                                  "................tt......"
                                  ".................tt....."
                                  "..................tt...."
                                  "...................tt..."
                                  "....................tt.."
                                  ".....................tt."
                                  "......................tt"
                                  "........................");

ART24(BATTERY, "........................"
               "........................"
               "........................"
               "........................"
               "........................"
               "ttttttttttttttttttt....."
               "tgggggggggggggggggt....."
               "tg***************gt....."
               "tg***************gt....."
               "tg***************gttt..."
               "tg***************gttt..."
               "tg***************gttt..."
               "tg***************gttt..."
               "tg***************gttt..."
               "tg***************gttt..."
               "tg***************gt....."
               "tg***************gt....."
               "tgggggggggggggggggt....."
               "ttttttttttttttttttt....."
               "........................"
               "........................"
               "........................"
               "........................"
               "........................");

ART24(BOLT, "........................"
            "........................"
            "............tttttttt...."
            "...........taaaaaat....."
            "..........taaaaaat......"
            ".........taaaaaat......."
            "........taaaaaat........"
            ".......taaaaaat........."
            "......taaaaaat.........."
            ".....taaaaaattttttt....."
            "....taaaaaaaaaaaat......"
            "....tttttttaaaaat......."
            "..........taaaat........"
            ".........taaaat........."
            "........taaaat.........."
            ".......taaat............"
            "......taaat............."
            ".....taat..............."
            ".....tat................"
            "....tt.................."
            "....t..................."
            "........................"
            "........................"
            "........................");

ART24(BLUETOOTH, "........................"
                 ".........aaaaaa........."
                 ".......aaaaaaaaaa......."
                 "......aaaaaaaaaaaa......"
                 ".....aaaaaaAAaaaaaa....."
                 ".....aaaaaaAAAaaaaa....."
                 ".....aaAaaaAAaAaaaa....."
                 ".....aaaAaaAAaaAaaa....."
                 ".....aaaaAaAAaaaAaa....."
                 ".....aaaaaAAAaaAaaa....."
                 ".....aaaaaaAAaAaaaa....."
                 ".....aaaaaaAAAaaaaa....."
                 ".....aaaaaaAAAaaaaa....."
                 ".....aaaaaaAAaAaaaa....."
                 ".....aaaaaAAAaaAaaa....."
                 ".....aaaaAaAAaaaAaa....."
                 ".....aaaAaaAAaaAaaa....."
                 ".....aaAaaaAAaAaaaa....."
                 ".....aaaaaaAAAaaaaa....."
                 ".....aaaaaaAAaaaaaa....."
                 "......aaaaaaaaaaaa......"
                 ".......aaaaaaaaaa......."
                 ".........aaaaaa........."
                 "........................");

ART24(MOUSE, "........................"
             "........tttttttt........"
             "......tthhhtthhhtt......"
             ".....thhhhhtthhhhht....."
             "....thhhhhhtthhhhhht...."
             "....thhhhhhtthhhhhst...."
             "....thhhhhhtthhhhhst...."
             "....thhhhhhtthhhhhst...."
             "....thhhhhhtthhhhhst...."
             "....tttttttttttttttt...."
             "....thhhhhhhhhhhhhst...."
             "....thhhhhhhhhhhhhst...."
             "....thhhhhhhhhhhhhst...."
             "....thhhhhhhhhhhhhst...."
             "....thhhhhhhhhhhhhst...."
             "....thhhhhhhhhhhhhst...."
             "....thhhhhhhhhhhhhst...."
             "....thhhhhhhhhhhhhst...."
             "....thhhhhhhhhhhhhst...."
             "....thhhhhhhhhhhhsst...."
             ".....thhhhhhhhhhsst....."
             "......ttsssssssstt......"
             "........tttttttt........"
             "........................");

ART24(KEYBOARD, "........................"
                "........................"
                "........................"
                "........................"
                "........................"
                "........................"
                "tttttttttttttttttttttttt"
                "thhhhhhhhhhhhhhhhhhhhhht"
                "thsshsshsshsshsshsshssht"
                "thsshsshsshsshsshsshssht"
                "thhhhhhhhhhhhhhhhhhhhhht"
                "thhsshsshsshsshsshsshhht"
                "thhsshsshsshsshsshsshhht"
                "thhhhhhhhhhhhhhhhhhhhhht"
                "thsshsssssssssssshsshhht"
                "thsshsssssssssssshsshhht"
                "thhhhhhhhhhhhhhhhhhhhhht"
                "tttttttttttttttttttttttt"
                "........................"
                "........................"
                "........................"
                "........................"
                "........................"
                "........................");

ART24(HEADPHONES, "........................"
                  "........................"
                  "........tttttttt........"
                  "......tttttttttttt......"
                  "....tttt........tttt...."
                  "...ttt............ttt..."
                  "..ttt..............ttt.."
                  "..tt................tt.."
                  ".tt..................tt."
                  ".tt..................tt."
                  ".tt..................tt."
                  ".tt..................tt."
                  "tttttt............tttttt"
                  "thhhht............thhhht"
                  "thhhht............thhhht"
                  "thhhht............thhhht"
                  "thhhst............thhhst"
                  "thhhst............thhhst"
                  "thhsst............thhsst"
                  "thssst............thssst"
                  "tttttt............tttttt"
                  "........................"
                  "........................"
                  "........................");

ART24(PHONE, "......tttttttttttt......"
             "......thhhhhhhhhht......"
             "......thhhtttthhht......"
             "......taaaaaaaaaat......"
             "......taaaaaaaaaat......"
             "......taaaaaaaaaat......"
             "......taaaaaaaaaat......"
             "......taaaaaaaaaat......"
             "......taaaaaaaaaat......"
             "......taaaaaaaaaat......"
             "......taaaaaaaaaat......"
             "......taaaaaaaaaat......"
             "......taaaaaaaaaat......"
             "......taaaaaaaaaat......"
             "......taaaaaaaaaat......"
             "......taaaaaaaaaat......"
             "......taaaaaaaaaat......"
             "......taaaaaaaaaat......"
             "......taaaaaaaaaat......"
             "......thhhhhhhhhht......"
             "......thhhhtthhhht......"
             "......thhhhtthhhht......"
             "......thhhhhhhhhht......"
             "......tttttttttttt......");

ART24(GAMEPAD, "........................"
               "........................"
               "........................"
               "........................"
               "........................"
               "........................"
               "....tttttttttttttttt...."
               "..tthhhhhhhhhhhhhhhhtt.."
               ".thhhhhhhhhhhhhhhhhhhht."
               ".thhhtthhhhhhhhhhaahhht."
               ".thhhtthhhhhhhhhhaahhht."
               ".thtttttthhhhhhaahhaaht."
               ".thtttttthhhhhhaahhaaht."
               ".thhhtthhhhhhhhhhaahhht."
               ".thhhtthhhhhhhhhhaahhht."
               ".thhhhhhhhhhhhhhhhhhhst."
               ".thhhhhhtttttttthhhhhst."
               ".thhhhst........thhhsst."
               "..tttttt........tttttt.."
               "........................"
               "........................"
               "........................"
               "........................"
               "........................");

ART24(COMPUTER, "........................"
                "........................"
                "........................"
                "...tttttttttttttttttt..."
                "...taaaaaaaaaaaaaaaat..."
                "...taaaaaaaaaaaaaaaat..."
                "...taaaaaaaaaaaaaaaat..."
                "...taaaaaaaaaaaaaaaat..."
                "...taaaaaaaaaaaaaaaat..."
                "...taaaaaaaaaaaaaaaat..."
                "...taaaaaaaaaaaaaaaat..."
                "...taaaaaaaaaaaaaaaat..."
                "...taaaaaaaaaaaaaaaat..."
                "...taaaaaaaaaaaaaaaat..."
                "...taaaaaaaaaaaaaaaat..."
                "...tttttttttttttttttt..."
                "..thhhhhhhhhhhhhhhhhht.."
                ".thhhhhhhhhhhhhhhhhhhst."
                "thhhhhhhhhhhhhhhhhhhhhst"
                "tttttttttttttttttttttttt"
                "........................"
                "........................"
                "........................"
                "........................");

ART24(PLUG, "........................"
            ".......tt......tt......."
            ".......tt......tt......."
            ".......tt......tt......."
            ".......tt......tt......."
            "....tttttttttttttttt...."
            "....thhhhhhhhhhhhhst...."
            "....thhhhhhhhhhhhhst...."
            "....thhhhhhhhhhhhhst...."
            "....thhhhhhhhhhhhhst...."
            "....thhhhhhhhhhhhhst...."
            "....thhhhhhhhhhhhhst...."
            "....thhhhhhhhhhhhsst...."
            "....tsssssssssssssst...."
            ".....tttttttttttttt....."
            "........tttttttt........"
            "...........tt..........."
            "...........tt..........."
            "...........tt..........."
            "...........ttt.........."
            "............ttt........."
            ".............ttt........"
            "..............tt........"
            "........................");

ART24(PEN, "........................"
           "....................ttt."
           "...................tsst."
           "..................tsst.."
           ".................taat..."
           "................taat...."
           "...............taat....."
           "..............taat......"
           ".............taat......."
           "............taat........"
           "...........taat........."
           "..........taat.........."
           ".........taat..........."
           "........taat............"
           ".......taat............."
           "......taat.............."
           ".....thht..............."
           "....thht................"
           "...thht................."
           "..ttt..................."
           ".tt....................."
           ".t......................"
           "........................"
           "........................");

ART24(TOUCHPAD, "........................"
                "........................"
                "........................"
                "........................"
                ".tttttttttttttttttttttt."
                ".thhhhhhhhhhhhhhhhhhhst."
                ".thhhhhhhhhhhhhhhhhhhst."
                ".thhhhhhhhhhhhhhhhhhhst."
                ".thhhhhhhhhhhhhhhhhhhst."
                ".thhhhhhhhhhhhhhhhhhhst."
                ".thhhhhhhhhhhhhhhhhhhst."
                ".thhhhhhhhhhhhhhhhhhhst."
                ".thhhhhhhhhhhhhhhhhhhst."
                ".thhhhhhhhhhhhhhhhhhhst."
                ".thhhhhhhhhhhhhhhhhhhst."
                ".tttttttttttttttttttttt."
                ".thhhhhhhhhtthhhhhhhhst."
                ".thhhhhhhhhtthhhhhhhhst."
                ".thhhhhhhhhtthhhhhhhhst."
                ".tttttttttttttttttttttt."
                "........................"
                "........................"
                "........................"
                "........................");

ART24(CUP, "........................"
           "........................"
           ".......tt....tt........."
           "......tt....tt.........."
           ".......tt....tt........."
           "......tt....tt.........."
           ".......tt....tt........."
           "........................"
           "...tttttttttttttt......."
           "...thhhhhhhhhhhhttttt..."
           "...thhhhhhhhhhhsttttt..."
           "...thhhhhhhhhhhst..tt..."
           "...thhhhhhhhhhhst..tt..."
           "...thhhhhhhhhhhst..tt..."
           "...thhhhhhhhhhhsttttt..."
           "...thhhhhhhhhhssttt....."
           "....thhhhhhhhhsst......."
           ".....thhhhhhhsst........"
           "......tttttttttt........"
           ".tttttttttttttttttttt..."
           ".tttttttttttttttttttt..."
           "........................"
           "........................"
           "........................");

ART24(WIRED, "........................"
             "........................"
             ".........tttttt........."
             ".........taaaat........."
             ".........taaaat........."
             ".........taaaat........."
             ".........taaaat........."
             ".........tttttt........."
             "...........tt..........."
             "...........tt..........."
             "...........tt..........."
             "...tttttttttttttttttt..."
             "...tttttttttttttttttt..."
             "...tt..............tt..."
             "...tt..............tt..."
             "tttttttt........tttttttt"
             "taaaaaat........taaaaaat"
             "taaaaaat........taaaaaat"
             "taaaaaat........taaaaaat"
             "taaaaaat........taaaaaat"
             "tttttttt........tttttttt"
             "........................"
             "........................"
             "........................");

ART24(TRANSFER, "........................"
                "........................"
                "........................"
                ".......tt......tt......."
                "......tttt.....tt......."
                ".....tttttt....tt......."
                "....tttttttt...tt......."
                ".......tt......tt......."
                ".......tt......tt......."
                ".......tt......tt......."
                ".......tt......tt......."
                ".......tt......tt......."
                ".......tt......tt......."
                ".......tt......tt......."
                ".......tt......tt......."
                ".......tt......tt......."
                ".......tt......tt......."
                ".......tt...tttttttt...."
                ".......tt....tttttt....."
                ".......tt.....tttt......"
                ".......tt......tt......."
                "........................"
                "........................"
                "........................");

ART24(LOGO, "........................"
            "........................"
            ".tttttttttttttttttttttt."
            ".taaaaaaaaaaaaaaaaaaaat."
            ".taAAAAAAAaaaaaaAaAaAat."
            ".taaaaaaaaaaaaaaaaaaaat."
            ".tttttttttttttttttttttt."
            ".tddddddddddddddddddddt."
            ".tddddddddddddddddddddt."
            ".tddhhddddddddddddddddt."
            ".tdddhhdddddddddddddddt."
            ".tddddhhddddddddddddddt."
            ".tdddddhhdddddddddddddt."
            ".tddddhhddddddddddddddt."
            ".tdddhhdddddddddddddddt."
            ".tddhhdddhhhhhhdddddddt."
            ".tddddddddddddddddddddt."
            ".tddddddddddddddddddddt."
            ".tddddddddddddddddddddt."
            ".tddddddddddddddddddddt."
            ".tttttttttttttttttttttt."
            "........................"
            "........................"
            "........................");

ART24(BACK, "...........t............"
            "..........tt............"
            ".........tht............"
            "........that............"
            ".......thaat............"
            "......thaaat............"
            ".....thaaaat............"
            "....thaaaaahtttttttttttt"
            "...thaaaaaaahhhhhhhhhhht"
            "..thaaaaaaaaaaaaaaaaaaat"
            ".thaaaaaaaaaaaaaaaaaaaat"
            "thaaaaaaaaaaaaaaaaaaaaat"
            "tsaaaaaaaaaaaaaaaaaaaaat"
            ".tsaaaaaaaaaaaaaaaaaaaat"
            "..tsaaaaaaaaaaaaaaaaaaat"
            "...tsaaaaaaassssssssssst"
            "....tsaaaaastttttttttttt"
            ".....tsaaaat............"
            "......tsaaat............"
            ".......tsaat............"
            "........tsat............"
            ".........tst............"
            "..........tt............"
            "...........t............");

ART24(FORWARD, "............t..........."
               "............tt.........."
               "............tht........."
               "............taht........"
               "............taaht......."
               "............taaaht......"
               "............taaaaht....."
               "tttttttttttthaaaaaht...."
               "thhhhhhhhhhhaaaaaaaht..."
               "taaaaaaaaaaaaaaaaaaaht.."
               "taaaaaaaaaaaaaaaaaaaaht."
               "taaaaaaaaaaaaaaaaaaaaaht"
               "taaaaaaaaaaaaaaaaaaaaast"
               "taaaaaaaaaaaaaaaaaaaast."
               "taaaaaaaaaaaaaaaaaaast.."
               "tsssssssssssaaaaaaast..."
               "ttttttttttttsaaaaast...."
               "............taaaast....."
               "............taaast......"
               "............taast......."
               "............tast........"
               "............tst........."
               "............tt.........."
               "............t...........");

ART24(RELOAD, "........................"
              "........................"
              "........ttt............."
              "......ttaat............."
              ".....taaaat............."
              "....taaaaat........tt..."
              "...taaaaattt......taat.."
              "...taaaat........taaaat."
              "..taaaat.........taaaat."
              "..taaat.........taaaaaat"
              "..taaat........taaaaaaat"
              "..taaat.......tttaaaaatt"
              "..taaat..........taaat.."
              "..taaat..........taaat.."
              "..taaat..........taaat.."
              "..taaaat........taaaat.."
              "...taaaat......taaaat..."
              "...taaaaattttttaaaaat..."
              "....taaaaaaaaaaaaaat...."
              ".....taaaaaaaaaaaat....."
              "......ttaaaaaaaatt......"
              "........tttttttt........"
              "........................"
              "........................");

ART24(HOME, "........................"
            "........................"
            "...........tt..........."
            "..........thht.........."
            ".........thaaht........."
            "........thaaaaht........"
            ".......thaaaaaaht......."
            "......thaaaaaaaaht......"
            ".....thaaaaaaaaaaht....."
            "....thaaaaaaaaaaaaht...."
            "...thaaaaaaaaaaaaaaht..."
            "..ttsaaaaaaaaaaaaaastt.."
            "....thhhhhhhhhhhhhht...."
            "....thhhhhhhhsssshht...."
            "....thhaaaahhsssshht...."
            "....thhaaaahhsssshht...."
            "....thhaaaahhsssshht...."
            "....thhaaaahhsssshht...."
            "....thhhhhhhhsssshht...."
            "....thhhhhhhhsssshht...."
            "....thhhhhhhhsssshht...."
            "....tttttttttttttttt...."
            "........................"
            "........................");

ART24(STOP, ".......tttttttttt......."
            "......taaaaaaaaaat......"
            ".....taaaaaaaaaaaat....."
            "....taaaaaaaaaaaaaat...."
            "...taaaaaaaaaaaaaaaat..."
            "..taaaaaaaaaaaaaaaaaat.."
            ".taaaaaaaaaaaaaaaaaaaat."
            "taaaaaaaaaaaaaaaaaaaaaat"
            "taaaaaaaaaaaaaaaaaaaaaat"
            "taaaaaaaaaaaaaaaaaaaaaat"
            "taaaaahhhhhhhhhhhhhaaaat"
            "taaaaahhhhhhhhhhhhhaaaat"
            "taaaaahhhhhhhhhhhhhaaaat"
            "taaaaahhhhhhhhhhhhhaaaat"
            "taaaaaaaaaaaaaaaaaaaaaat"
            "taaaaaaaaaaaaaaaaaaaaaat"
            "taaaaaaaaaaaaaaaaaaaaaat"
            ".taaaaaaaaaaaaaaaaaaaat."
            "..taaaaaaaaaaaaaaaaaat.."
            "...taaaaaaaaaaaaaaaat..."
            "....taaaaaaaaaaaaaat...."
            ".....taaaaaaaaaaaat....."
            "......taaaaaaaaaat......"
            ".......tttttttttt.......");

ART24(KEY, "........................"
           "........................"
           "........................"
           "........................"
           "........................"
           "....tttt................"
           "..ttwwwwtt.............."
           "..twwttwwt.............."
           ".twwt..twwt............."
           ".twt....twwttttttttttttt"
           ".twt....twwwwwwwwwwwwwwt"
           ".twt....twwttttwwwtttwwt"
           ".twwt..twwt....twt...twt"
           "..twwttwwt.....twt...twt"
           "..ttwwwwtt.....twt...twt"
           "....tttt.......ttt...ttt"
           "........................"
           "........................"
           "........................"
           "........................"
           "........................"
           "........................"
           "........................"
           "........................");

ART24X(ctui_look_picto_big_key_broken, "........................"
                                       "........................"
                                       "........................"
                                       "........................"
                                       "........................"
                                       "....tttt................"
                                       "..ttwwwwtt.............."
                                       "..twwttwwt.............."
                                       ".twwt..twwt............."
                                       ".twt....twwtt..........."
                                       ".twt....twwwt..........."
                                       ".twt....twwtt..........."
                                       ".twwt..twwt....ttttttttt"
                                       "..twwttwwt.....twwwwwwwt"
                                       "..ttwwwwtt.....ttwwwtttt"
                                       "....tttt.........twt...t"
                                       ".................twt...t"
                                       ".................twt...t"
                                       ".................ttt...t"
                                       "........................"
                                       "........................"
                                       "........................"
                                       "........................"
                                       "........................");

ART24(INFO, "........................"
            "...........tt..........."
            ".......tttthhtttt......."
            ".....tthhhhhhhhhhtt....."
            "....thhhhhaaahhhhhht...."
            "...thhhhhhaaahhhhhhht..."
            "..thhhhhhhaaahhhhhhhht.."
            ".thhhhhhhhhhhhhhhhhhhht."
            ".thhhhhhhhaaahhhhhhhhht."
            ".thhhhhhhhaaahhhhhhhhht."
            ".thhhhhhhhaaahhhhhhhhht."
            ".thhhhhhhhaaahhhhhhhhht."
            ".thhhhhhhhaaahhhhhhhhht."
            ".thhhhhhhhaaahhhhhhhhht."
            "..thhhhhhhaaahhhhhhhht.."
            "...thhhhhhaaahhhhhhht..."
            "...tthhhhhaaahhhhhhtt..."
            ".....thhhhhhhhhhhht....."
            "......tttthhhhtttt......"
            "......t...tttt.........."
            "........................"
            "........................"
            "........................"
            "........................");

ART24(WARNING, "........................"
               "...........tt..........."
               "...........tt..........."
               "..........twwt.........."
               "..........twwt.........."
               ".........twwwwt........."
               "........twwwwwwt........"
               "........twwwwwwt........"
               ".......twwtttwwwt......."
               ".......twwtttwwwt......."
               "......twwwtttwwwwt......"
               "......twwwtttwwwwt......"
               ".....twwwwtttwwwwwt....."
               "....twwwwwtttwwwwwwt...."
               "....twwwwwtttwwwwwwt...."
               "...twwwwwwtttwwwwwwwt..."
               "...twwwwwwwwwwwwwwwwt..."
               "..twwwwwwwwwwwwwwwwwwt.."
               "..twwwwwwwwwwwwwwwwwwt.."
               ".twwwwwwwwtttwwwwwwwwwt."
               "twwwwwwwwwtttwwwwwwwwwwt"
               "twwwwwwwwwtttwwwwwwwwwwt"
               "tttttttttttttttttttttttt"
               "........................");

ART24(ERROR, "........................"
             "........tttttttt........"
             "......ttaaaaaaaatt......"
             ".....taaaaaaaaaaaat....."
             "....taaaaaaaaaaaaaat...."
             "...taaaaaaaaaaaaaaaat..."
             "..taahhhaaaaaaaahhhaat.."
             "..taaahhhaaaaaahhhaaat.."
             ".taaaaahhhaaaahhhaaaaat."
             ".taaaaaahhhaahhhaaaaaat."
             ".taaaaaaahhhhhhaaaaaaat."
             ".taaaaaaaahhhhaaaaaaaat."
             ".taaaaaaaahhhhaaaaaaaat."
             ".taaaaaaahhhhhhaaaaaaat."
             ".taaaaaahhhaahhhaaaaaat."
             ".taaaaahhhaaaahhhaaaaat."
             "..taaahhhaaaaaahhhaaat.."
             "..taahhhaaaaaaaahhhaat.."
             "...taaaaaaaaaaaaaaaat..."
             "....taaaaaaaaaaaaaat...."
             ".....taaaaaaaaaaaat....."
             "......ttaaaaaaaatt......"
             "........tttttttt........"
             "........................");

const char *const ctui_look_picto_big[CTUI_LOOK_PICTOS] = {
    [CTUI_LOOK_PICTO_SPEAKER] = SPEAKER,
    [CTUI_LOOK_PICTO_MIC] = MIC,
    [CTUI_LOOK_PICTO_BATTERY] = BATTERY,
    [CTUI_LOOK_PICTO_BOLT] = BOLT,
    [CTUI_LOOK_PICTO_BLUETOOTH] = BLUETOOTH,
    [CTUI_LOOK_PICTO_MOUSE] = MOUSE,
    [CTUI_LOOK_PICTO_KEYBOARD] = KEYBOARD,
    [CTUI_LOOK_PICTO_HEADPHONES] = HEADPHONES,
    [CTUI_LOOK_PICTO_PHONE] = PHONE,
    [CTUI_LOOK_PICTO_GAMEPAD] = GAMEPAD,
    [CTUI_LOOK_PICTO_COMPUTER] = COMPUTER,
    [CTUI_LOOK_PICTO_PLUG] = PLUG,
    [CTUI_LOOK_PICTO_PEN] = PEN,
    [CTUI_LOOK_PICTO_TOUCHPAD] = TOUCHPAD,
    [CTUI_LOOK_PICTO_CUP] = CUP,
    [CTUI_LOOK_PICTO_WIRED] = WIRED,
    [CTUI_LOOK_PICTO_TRANSFER] = TRANSFER,
    [CTUI_LOOK_PICTO_LOGO] = LOGO,
    [CTUI_LOOK_PICTO_BACK] = BACK,
    [CTUI_LOOK_PICTO_FORWARD] = FORWARD,
    [CTUI_LOOK_PICTO_RELOAD] = RELOAD,
    [CTUI_LOOK_PICTO_HOME] = HOME,
    [CTUI_LOOK_PICTO_STOP] = STOP,
    [CTUI_LOOK_PICTO_KEY] = KEY,
    [CTUI_LOOK_PICTO_INFO] = INFO,
    [CTUI_LOOK_PICTO_WARNING] = WARNING,
    [CTUI_LOOK_PICTO_ERROR] = ERROR,
};
